codecov:
  require_ci_to_pass: false
  notify:
    after_n_builds: 3
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "diff,flags"
  behavior: default
  require_changes: no
