# Required by Read The Docs
version: 2

formats: all

# Use an image with modern OpenSSL.
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  # Use an empty install section to avoid RTD from picking up a non-python
  # requirements.txt file.
  install: []
