# Required by Read The Docs
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - sphinx-rtd-theme

sphinx:
  builder: html
  configuration: doc/userguide/conf.py
  fail_on_warning: false

formats: all
